clear
clf

% --- create arm ---
[face_base,V_staender] = loadCAD('cad/cad_base.stl');
[face_upperArm,V_oberarm] = loadCAD('cad/cad_upperArm.stl');
[face_lowerArm,V_unterarm] = loadCAD('cad/cad_lowerArm.stl');
[face_hand, V_hand] = loadCAD('cad/cad_hand.stl');
[face_thumb,V_daumen] = loadCAD('cad/cad_thumb.stl');
[face_garbage,V_garbage] = loadCAD('cad/cad_garbage1.stl');

% setting internal coordinate systems
X = [0, 1, 0, 0;
     0, 0, 1, 0;
     0, 0, 0, 1;
     1, 1, 1, 1];

schulterK = tl(0,0,700)*X;
ellbogenK = tl(500,0,640)*X;
handK = tl(1000,0,640)*X;
fingerK = tl(1055,0,540)*X;
garbageK = tl(1100,0,540)*X;


face = struct('base', face_base,...
              'upperArm', face_upperArm,...
              'lowerArm', face_lowerArm,...
              'hand', face_hand,...
              'thumb', face_thumb,...
              'garbage', face_garbage);

robo = struct('V_Staender', V_staender,...
               'V_Oberarm', V_oberarm,...
               'V_Unterarm',V_unterarm,...
               'V_Hand', V_hand,...
               'V_Daumen', V_daumen,...
               'V_Garbage', V_garbage,...
               'SchulterK', schulterK,...
               'EllbogenK', ellbogenK,...
               'HandK', handK,...
               'FingerK', fingerK,...
               'GarbageK', garbageK,...
               'garbageGrabed', false,...
               'pos_angles', [0, 0, 0],...
               'height', 640,...
               'upperArm_len', 500,...
               'lowerArm_len', 500,...
               'hand_len', 150);

robo.graphics = initView(robo, face);


robo = moveRobo(robo, [600, 315, 85]);
robo = grab(robo);
pause(1)
robo = moveRobo(robo, [-500, -500, 600]);
robo = letGo(robo);
pause(1)
robo = moveRobo(robo, [1000, 0, 300]);
